### ISSUE TITLE
tqdm' object has no attribute 'pos'"

### ISSUE THREAD

**Issue by rick020** [edumucelli/spotify-worldwide-ranking#1]
Running this code(Python 2.7) will produce the following error: Exception AttributeError: "'tqdm' object has no attribute 'pos'" in <object repr() failed> ignored.

How can I solve this?

**Comment by edumucelli** [comment]
@rick020 I can't reproduce your problem. I have tried on Python 2.7.12. What are the steps you did to get such error?

Basically what you have to do is to download the project as a zip, extract it then `python spotify.py`
